### ISSUE TITLE
Usage 2, setting attributes from the recipe level

### ISSUE THREAD

**Issue by Joseph-R** [rackspace-cookbooks/chef-slack_handler#1]
I originally had this working setting everything for Usage 2 at the environment level, except the following, configured in the cookbook attribute file:

```
case node.chef_environment
when "staging" 
  node.default['chef_client']['handler']['slack']['webhooks']['name'].push('webhook1')
  node.default['chef_client']['handler']['slack']['webhooks']['name'].push('webhook2')
when "production"
  node.default['chef_client']['handler']['slack']['webhooks']['name'].push('webhook1')
  node.default['chef_client']['handler']['slack']['webhooks']['name'].push('webhook2')
end
```

That worked well, until I attempted to factor it out to the recipe level.  My recipe looked like this:

```
# Configures Slack integration
# https://github.com/rackspace-cookbooks/chef-slack_handler

include_recipe "slack_handler"

# Send successes to #staging and #production.  Send failed runs to #errors.
case node.chef_environment
when "staging" 
  node.default['chef_client']['handler']['slack']['webhooks']['name'].push('webhook1')
  node.default['chef_client']['handler']['slack']['webhooks']['name'].push('webhook2')
when "production"
  node.default['chef_client']['handler']['slack']['webhooks']['name'].push('webhook1')
  node.default['chef_client']['handler']['slack']['webhooks']['name'].push('webhook2')
end

# Note: Verbosity is configured at the environment level.   
# Options are 'basic', 'elapsed' and 'resources'.
```

Running it this way broke something.  I'm not sure what.  We no longer get slack notifications to either of the three channels we have configured (#staging, #production, and #errors).

[Output](https://gist.github.com/Joseph-R/4aceb502917dfb6daf8b).

Not sure if this is a problem with the code, or my use case, or ??  Maybe I missed something obvious moving the attributes out of the attribute file?  

I'd appreciate a little guidance.

**Comment by martinb3** [comment]
Hi there -- I think part of the problem is you're using `node.default` _after_ including the recipe. Can you set those values before you run the recipe (or put the attribute-setting into an attribute file under `attributes/<file>.rb`)?

Also, I'd highly recommend setting those to known values, as opposed to appending to an array with unknown initial contents, e.g.:

```
node.default['chef_client']['handler']['slack']['webhooks']['name'] = ['webhook1', 'webhook2']
include_recipe "slack_handler"
```

**Comment by Joseph-R** [comment]
Hey @martinb3 , thanks for your feedback.  

`I think part of the problem is you're using node.default after including the recipe. Can you set those values before you run the recipe (or put the attribute-setting into an attribute file under attributes/<file>.rb)?`

D'oh!  Yep.  Obvious error on my part.  Fixed that.

Still wasn't completely successful pulling these configs out of the attribute file, but I got pulled off this and never circled back around.  

We can close this if you want.  I'll open another ticket if I have any further issue.

**Comment by martinb3** [comment]
Thanks for the update! Cheers!
