### ISSUE TITLE
Incorrect commit tagged as 0.1.0

### ISSUE THREAD

**Issue by nicwaller** [rackspace-cookbooks/chef-slack_handler#10]
The 0.1.0 tag on this repo is not associated with the right commit. I downloaded the 0.1.0 cookbook from Supermarket and it seems to correspond with commit f32996dddb2319198d968dcc492b36567460e630. 

Currently in this repo, the 0.1.0 tag is on b3f273f70e899d979dd06ae581f05a3f9e8166e6. That's a difference of 14 commits.

It's just a minor thing, but it would be nice to have it corrected.

**Comment by martinb3** [comment]
Thanks @nicwaller -- I've fixed the tag. Sorry about that! :)
