### ISSUE TITLE
default['chef_client']['handler']['slack']['fail_only'] is ignored when using webhooks

### ISSUE THREAD

**Issue by jujugrrr** [rackspace-cookbooks/chef-slack_handler#18]
Different issue than #14 
While testing the PR above I noticed webhooks handler is not looking at `default['chef_client']['handler']['slack']['fail_only']` but only at `default['chef_client']['handler']['slack']['webhooks']['mywebhook']['fail_only']`

**Comment by jujugrrr** [comment]
Because : https://github.com/rackspace-cookbooks/chef-slack_handler/blob/master/files/default/slack_handler_webhook.rb#L38
And https://github.com/rackspace-cookbooks/chef-slack_handler/blob/master/files/default/slack_handler_webhook.rb#L42

I'd say the generic one should be applied unless there is a specific one

**Comment by martinb3** [comment]
> I'd say the generic one should be applied unless there is a specific one

Agreed!

**Comment by cknowles** [comment]
I noticed a couple of similar issues in pull https://github.com/rackspace-cookbooks/chef-slack_handler/pull/19 which I will be sorting out today.

**Comment by cknowles** [comment]
Resolved in 0.6.0

**Comment by jujugrrr** [comment]
> Resolved in 0.6.0

Thanks
