### ISSUE TITLE
Add support for deployment start message

### ISSUE THREAD

**Issue by cknowles** [rackspace-cookbooks/chef-slack_handler#20]
It's nice having a message when the deploy finishes, an optional message on deploy start would be great too for some cases.

**Comment by martinb3** [comment]
There's already a few different cookbooks out there that provide a resource to do this. I'm not sure this cookbook needs to start competing with them, but maybe it would make this one the best out there too.

**Comment by cknowles** [comment]
I was having a look around for one, any suggestions for a good one? I think it'd be good to align the messaging and potentially even support custom events sent from anywhere inside the calling cookbook. I had a look through the chef start handlers earlier but couldn't find any decent examples. Are the cookbooks you refer to generally using start handlers?

**Comment by martinb3** [comment]
Well, you mentioned deploys, and there's a few that have a custom resource you can feed into one of the blocks of the various deploy resources, e.g.

```
deploy 'foo' do
  before_start do
    slack_message 'its happening'
  end
...
end
```

So they actually line up more with deploying than the start of the chef run. I agree, if you're referring to the start of the chef run, that there's not much out there.

Regarding the custom resources, there's:
https://github.com/rackspace-cookbooks/chatops_notify
https://github.com/KennaSecurity/chef-slack

**Comment by cknowles** [comment]
I've had a go at this, inspired by the work done [here](https://github.com/onddo/chef-handler-zookeeper) which is in turn inspired by [this one](https://github.com/needle-cookbooks/chef-sensu-handler). Please could you have a look through and let me know what you think? If the general idea is ok, I will add some tests plus support for the Slackr handler and doc updates.

The output in Slack looks a bit like this:
`:gear: Chef client run started on webhook-debian-79 using cookbooks ["slack_handler 0.6.0", "chef_handler 1.3.0"]`

**Comment by martinb3** [comment]
@c-knowles I made one comment, but it looks useful to me.

**Comment by martinb3** [comment]
The draft looks good to me, @c-knowles. Let me know when/if you're ready for a PR.

**Comment by cknowles** [comment]
Resolved in https://github.com/rackspace-cookbooks/chef-slack_handler/pull/24
