### ISSUE TITLE
Add support for environment

### ISSUE THREAD

**Issue by cknowles** [rackspace-cookbooks/chef-slack_handler#23]
In some environments, the node names are reasonably obscure so it may be good to include an option to send the chef environment. I believe this is usually accessed via `node.chef_environment`.

**Comment by shortdudey123** [comment]
@c-knowles how are you envisioning this on the slack end?
`"#{node.chef_environment}:#{node.name}"` vs `"#{node.name}"`?

**Comment by cknowles** [comment]
I've got most of this ready in my fork but not pushed it yet. I was thinking `"#{node.name} (#{node.chef_environment})"` where the environment is optional but perhaps putting the environment first makes more sense. Let me know what you think and I can change it before I finalise the push.

**Comment by shortdudey123** [comment]
Personally i think env first makes sense, however with the env in `()` after would work too

**Comment by cknowles** [comment]
How about we go with the explicit version of `"env #{node.chef_environment}, node #{node.name}"`?

**Comment by cknowles** [comment]
Resolved in https://github.com/rackspace-cookbooks/chef-slack_handler/pull/24
