### ISSUE TITLE
undefined method `run_context' for Chef:Class

### ISSUE THREAD

**Issue by glensc** [rackspace-cookbooks/chef-slack_handler#29]
as there's no minimum chef version mentioned, not sure that is the issue.

i've configured to use webhook mode and get such error at the end of the run:

```
Running handlers:
[2016-05-31T12:46:33+03:00] WARN: Failed to send message to Slack: undefined method `run_context' for Chef:Class
  - Chef::Handler::Slack
  - SyslogReporting
Running handlers complete
```

```
 # chef-client --version
Chef: 11.16.4
```

**Comment by cknowles** [comment]
I think that was changed in https://github.com/rackspace-cookbooks/chef-slack_handler/pull/22 but not sure what the minimum version should be. Using v12 here.

**Comment by martinb3** [comment]
We've definitely released the changes in #22.

**Comment by martinb3** [comment]
Chef 12.x is about 1.5 years old, so I've only been testing on it. It wouldn't surprise me if there was something broken in Chef 11.x. I'd be happy to merge PRs to add compatibility back, if so. 👍

**Comment by glensc** [comment]
i was investigating this, and i fixed it locally by saving `run_context` from `report()` locally as `@run_context`, instead of "asking" it from chef internals. this also involved moving `@util` creation to `report` method.

would you accept such rewrite as PR?

**Comment by martinb3** [comment]
@glensc Would you consider building a branch that exercises the issue? I'd like to understand further what's happening here. The chef run_context object was definitely around in Chef 11.x.

**Comment by glensc** [comment]
yes, but not in exact place you're taking it now. and i feel it's using it's internal structures is unreliable. and storing it as instance property `@run_context` makes rest of the code also more readable (don't need to pass it around between methods)

ok, i'll try to clean it up and show the branch, but that tomorrow, hopefully.

**Comment by kjwierenga** [comment]
This is currently blocking me from using chef-slack_handler with Chef v11.12.4

**Comment by kjwierenga** [comment]
Thanks @glensc. I actually arrived at almost the same solution before seeing your commit 😄

**Comment by glensc** [comment]
:dancer:

**Comment by glensc** [comment]
closing as #35 was merged
