### ISSUE TITLE
new version of chef

### ISSUE THREAD

**Issue by RayMeibergen** [rackspace-cookbooks/chef-slack_handler#3]
got this error. can you check this.

  Chef::Exceptions::ValidationFailed

---

  Option action must be equal to one of: enable, disable!  You passed :nothing.
  Cookbook Trace:                                                                                                                                                                                  ---------------
    /var/chef/cache/cookbooks/slack_handler/recipes/default.rb:47:in `block in from_file'                                                                                                            /var/chef/cache/cookbooks/slack_handler/recipes/default.rb:42:in`from_file'

  Relevant File Content:

---

  /var/chef/cache/cookbooks/slack_handler/recipes/default.rb:
                                                                                                                                                                                                    40:  end.run_action(:create)
   41:                                                                                                                                                                                              42:  chef_handler "Chef::Handler::Slack" do
   43:    source handler_file
   44:    arguments [
   45:                node['chef_client']['handler']['slack']
   46:              ]
   47>>   action :nothing
   48:  end.run_action(:enable)
   49:

**Comment by RayMeibergen** [comment]
chef version was Chef: 12.4.0.rc.2

**Comment by martinb3** [comment]
In currently released versions, `:nothing` is [common to all resources](https://docs.chef.io/resource_common.html). It appears 12.4.0.rc.2 was released 6 days ago.

**Comment by RayMeibergen** [comment]
OK! are you gonna fix this in the future?

**Comment by martinb3** [comment]
This appears to a bug in chef, but I've opened an issue upstream with them to confirm.

**Comment by RayMeibergen** [comment]
thanks for report to chef!

**Comment by goacid** [comment]
+1

```
gem list|grep chef
chef (11.16.0)
chef-config (12.4.0)
chef-zero (4.2.3, 2.2.1)
```

**Comment by martinb3** [comment]
I believe this has been fixed upstream in chef.
