### ISSUE TITLE
Integrating Slack Handler into client.rb?

### ISSUE THREAD

**Issue by petewilcock** [rackspace-cookbooks/chef-slack_handler#32]
I'd like to integrate the slack handler directly into client.rb and not have it run as part of the cookbook. I want the handler to catch convergence failures and other errors that might occur before a runlist even gets going. I'm not clear on what I need to do this, although my initial attempt looks something like this:

In `/etc/chef/client.d` in a file called `slack.rb`

```
require 'rubygems'
require '/var/chef/handlers/slack_handler_webhook'
​
slack_handler = Chef::Handler::Slack.new
​
start_handlers << slack_handler
report_handlers << slack_handler
exception_handlers << slack_handler
```

But this is sofar not working. Can I integrate this in this way?

**Comment by martinb3** [comment]
Hello @petewilcock -- I haven't actually configured handlers this way before, but [based on the documentation](https://docs.chef.io/handlers.html), it seems like what you're doing should work. Are you getting an error when chef-client runs? Everything else looks like it should work.

Two things that differ from the examples -- (1) this isn't a gem and (2) this code requires the slackr gem. Is the second item already satisfied by installing that gem into the chef embedded ruby? The only other thing I can think of to try would be to install the handler as a gem.

**Comment by petewilcock** [comment]
Hi Martin - this isn't working currently, but I suspect it might be because I haven't provided the required attributes for the webhook URL and its name. I'm not quite sure how to pass these into the method in this context. Do you have any idea?

**Comment by petewilcock** [comment]
My reason for doing this is because I want to catch exceptions that occur on convergence, where the slack handler recipe wouldn't have a chance to run and so I wouldn't get a notification. If I can set it up in the client configuration I should always receive these once the handler is installed on the machine - I think!

**Comment by martinb3** [comment]
From what I can gather, the only way to set attributes in `client.rb` is to use the `json_attribs` setting and specify attributes in a JSON file elsewhere. You could likely also apply node attributes via a role or environment that would be loaded before any recipes run.

**Comment by martinb3** [comment]
Let us know if you were able to solve this and how, for future visitors -- but I'll go ahead and close this now. Thank you for the discussion!
