### ISSUE TITLE
no implicit conversion of Chef::DelayedEvaluator into String

### ISSUE THREAD

**Issue by ostsjoe** [rackspace-cookbooks/chef-slack_handler#37]
I'm running into this in ubuntu 14.04, chef 12.13.37. Worked fine in chef 12.6.
`  \* cookbook_file[/var/chef/handlers/slack_handler_util.rb] action create

```
================================================================================
Error executing action `create` on resource 'cookbook_file[/var/chef/handlers/slack_handler_util.rb]'
================================================================================

TypeError
---------
no implicit conversion of Chef::DelayedEvaluator into String

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/slack_handler/recipes/default.rb:42:in `from_file'
/var/chef/cache/cookbooks/moxi-slack/recipes/default.rb:14:in `from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/slack_handler/recipes/default.rb

 37: cookbook_file "#{node['chef_handler']['handler_path']}/slack_handler_util.rb" do
 38:   source 'slack_handler_util.rb'
 39:   mode "0600"
 40:   action :nothing
 41:   # end
 42: end.run_action(:create)

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/slack_handler/recipes/default.rb:37:in `from_file'

cookbook_file("/var/chef/handlers/slack_handler_util.rb") do
  provider Chef::Provider::CookbookFile
  action [:nothing]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  source "slack_handler_util.rb"
  declared_type "cookbook_file"
  cookbook_name "slack_handler"
  recipe_name "default"
  mode "0600"
  atomic_update #<Chef::DelayedEvaluator:0x00000001d8ce98@/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource/file.rb:53>
  path #<Chef::DelayedEvaluator:0x00000001d8df78@/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/property.rb:180>
end

Platform:
---------
x86_64-linux`
```

I also had a similar error with with chef_handler, but was able to resolve the issue by changing that to use just directory instead of remote_directory to make the handler_path on disk. The newer version of chef doesn't seem to appreciate the run_action with more complex resources. Interestingly if I run just the slack integration recipe by itself, it doesn't fail. But in a full chef run it does.

**Comment by martinb3** [comment]
From what I've read so far, this looks like a bug in chef, similar to [this one](https://github.com/chef/chef/issues/3703).

**Comment by ostsjoe** [comment]
Looks like that's the case. Seems to still be a problem in the 12.14 branch as well. Wonder if there are any workarounds in the meantime.

**Comment by artursmolarek** [comment]
The same issue on the newest version of ChefDK:

```
➜  ~ chef --version
Chef Development Kit Version: 0.18.30
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.1.0
kitchen version: 1.13.2
```

Any workarounds?

**Comment by martinb3** [comment]
Hi folks -- I've reported this upstream; I'm not sure what else to do for it, at this point.

**Comment by martinb3** [comment]
Hi folks -- it looks like they've accepted the bug upstream as an issue. If you have full stack traces, could you please go and provide them in the linked issue on chef/chef? Thanks all!

**Comment by ostsjoe** [comment]
Currently with slack_handler 0.8.0 and chef_handler 2.1.0, tested with both chef-client 12.6.0 and 12.19.36 I'm no longer running into this issue. It may have been related to a conflicting cookbook, autofs. Thanks for looking into this @martinb3
