### ISSUE TITLE
WARN: Failed to send message to Slack: undefined local variable or method `run_context' for #<SlackHandlerUtil:0x00000001d8e1d0>

### ISSUE THREAD

**Issue by BetaFold3** [rackspace-cookbooks/chef-slack_handler#38]
Hi,

I met this error when using slack_handler.

Here's the log:

> Recipe: chef_handler::default
> - remote_directory[/var/chef/handlers] action create
>   Recipe: <Dynamically Defined Resource>
> 
> ```
> * cookbook_file[/var/chef/handlers/README] action create (up to date)
>  (up to date)
> ```
> 
> Recipe: slack_handler::default
> - cookbook_file[/var/chef/handlers/slack_handler_util.rb] action create (up to date)
> - cookbook_file[/var/chef/handlers/slack_handler_webhook.rb] action create (up to date)
> - chef_handler[Chef::Handler::Slack] action enable
>   - disable Chef::Handler::Slack as a start handler
>   - disable Chef::Handler::Slack as a report handler
>   - disable Chef::Handler::Slack as a exception handler
>   - load Chef::Handler::Slack from /var/chef/handlers/slack_handler_webhook.rb
>   - enable chef_handler[Chef::Handler::Slack] as a start handler
>   - enable chef_handler[Chef::Handler::Slack] as a report handler
>   - enable chef_handler[Chef::Handler::Slack] as a exception handler
> - ruby_block[trigger_start_handlers] action create[2016-09-16T10:54:52+00:00] WARN: Failed to send message to Slack: undefined local variable or method `run_context' for #SlackHandlerUtil:0x00000001d8e1d0

Chef client version

> $ chef -v
> Chef Development Kit Version: 0.9.0
> chef-client version: 12.5.1
> berks version: 4.0.1
> kitchen version: 1.4.2

Here's the config I've put on node config:

> "chef_client": {
>             "handler": {
>                 "slack": {
>                     "webhooks": {
>                         "name": ["webhook1"],
>                         "webhook1": {
>                             "url": "[MY HOOK URL]"
>                         }
>                     },
>                     "timeout": 30,
>                     "username": "Chef Bot",
>                     "icon_emoji": ":fork_and_knife:",
>                     "fail_only": false,
>                     "send_start_message": true,
>                     "message_detail_level": "resource",
>                     "cookbook_detail_level": "all",
>                     "send_environment": true
>                 }
>             }
>         }

Please tell if you need to provide more information.
Thank you.

**Comment by treyx** [comment]
Same exact issue. We are using OpsWorks Chef and I'm getting the same `run_context` exception. Anyone have any ideas on how to solve?

**Comment by shortdudey123** [comment]
@treyx what cookbook version? and can you provide a full stacktrace?

**Comment by treyx** [comment]
@shortdudey123 I'm using the latest version of the cookbook (0.8). 

Here's the relevant stack trace. Let me know if I'm missing something 

https://gist.github.com/treyx/4c018e8c420499489ce9ec2ac5ca38fd

**Comment by shortdudey123** [comment]
Can you provide a stack trace? running chef-client at debug level should be able to provide it
Also, what chef client version?

**Comment by treyx** [comment]
@shortdudey123 I've updated the original gist [here](https://gist.github.com/treyx/4c018e8c420499489ce9ec2ac5ca38fd)

**Comment by treyx** [comment]
@shortdudey123 chef-client version is `12.12.15`

**Comment by treyx** [comment]
I've fixed this issue with PR #41 

cc: @tuannh99 @shortdudey123

**Comment by shannonrdunn** [comment]
We are affected by this, any news on implementation, looks like #41 fixes it?

**Comment by martinb3** [comment]
#41 breaks compatibility with older Chef, which we had just added at the time. @treyx any update on making it backwards compatible?

**Comment by treyx** [comment]
@martinb3 I should be able to fix that PR sometime next week. Apologies for the delay. 

cc: @shannonrdunn

**Comment by jazaval** [comment]
I've submitted #52, which is compatible with at least Chef 11.
