### ISSUE TITLE
Support for conditional slack notifications?

### ISSUE THREAD

**Issue by spuder** [rackspace-cookbooks/chef-slack_handler#4]
I'm using this cookbook to send reports to slack every time chef runs. Is there a way to send a conditional notification, say if a specific was updated?

If not, then are there any plans to add a LWRP (or custom resource) that can be notified / subscribed to?

**Comment by martinb3** [comment]
It does not currently support that feature. I think we'd be glad to merge/review a PR that added this functionality.

**Comment by spuder** [comment]
Looks like this other cookbook supports LWRP

https://github.com/risk-io/chef-slack

It would be nice if those cookbook were combined so I didn't have to add 2 more dependencies to my cookbooks, but for now that one works.
