### ISSUE TITLE
Handler does not alert on custom exceptions

### ISSUE THREAD

**Issue by MaxFlanders** [rackspace-cookbooks/chef-slack_handler#51]
I am including a very basic check that chef environment is set on all of my nodes, which looks like this:

    if node.environment() == "_default"
      raise "Please re-bootstrap your node including the --environment parameter."
    end

While this does successfully kill the chef-client run in these cases, it does not cause the chef-slack handler to send any event to our slack channel. I have tested other errors, and also manually triggering the slack webhook with a curl request and those all still work.

Do I need to reformat my exception somehow to get chef-slack handler to recognize it??

Version 0.7.1

**Comment by martinb3** [comment]
Hi there -- are you raising this exception _after_ the slack_handler cookbook runs? If you're doing this first, the handler won't be installed yet.

**Comment by MaxFlanders** [comment]
You are correct that was the issue. Chef slack handler is now in the first slot in the run list to catch all exceptions.

Thank you!

**Comment by martinb3** [comment]
Perfect. Happy to help! 👍
